### PR TITLE
client.UpdateService needed v2 of ServiceUpdateInput

### PR DESCRIPTION
**Pull request by davidbloss**
Resolves #

### Checklist

- [ ] I have run this code, and it appears to resolve the stated issue.
- [ ] This PR has no user interface changes or has already received approval from product management to change the interface.
- [ ] Make a [changie](https://github.com/OpsLevel/cli/blob/main/CONTRIBUTING.md#changie-change-log-generation) entry that explains the customer facing outcome of this change

### CODE REVIEW

**Comment by rocktavious** [comment]
@davidbloss so after extensive testing with the latest released version I was not able to reproduce the originally stated issue.  Then after testing with this version it seems to work exactly the same.  So i'm not sure whats going on but either way we should be using the updated input payload and i've taken to fixing the task file to rip out the nilaway and forced opslevel-go update.

Thoughts?

**Comment by davidbloss** [comment]
> ... i've taken to fixing the task file to rip out the nilaway and forced opslevel-go update.
> 
> Thoughts?

Agreed that taking out nilaway from the taskfile is a great move. But I think we should keep the opslevel-go version update task for now, and remove it's [actual usage on line 30](https://github.com/OpsLevel/kubectl-opslevel/pull/321/files#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eL30). This logic will likely be helpful when we make the various tool deploys more automated later on

**Comment by rocktavious** [comment]
@davidbloss I only removed `has-latest-opslevel-dependencies` which is a check not a thing that updates.  There is still a non-internal task `update-opslevel-deps` to help with manually choosing to update the deps.

**Comment by davidbloss** [comment]
Replaced by [PR #325](https://github.com/OpsLevel/kubectl-opslevel/pull/325)

**Pull request closed without merging**
